name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        # Install Dependencies
    #from https://github.com/danielecook/seq-collection/blob/master/.github/workflows/build.yml
    - name: Install dependencies (Linux)
      #if: runner.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get -qy install make build-essential cmake libncurses-dev ncurses-dev libbz2-dev lzma-dev liblzma-dev \
             curl libssl-dev libtool autoconf automake libcurl4-openssl-dev
    - name: build
      run: /bin/bash -x ./build.sh
    - name: test
      run: /bin/bash tests/test.sh
