name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: /bin/bash -x ./build_no_container.sh
    - name: test
      run: /bin/bash -x tests/test.sh
